name: QA Auto Integration Check (07-21-2026)

on:
  push:
    branches:
      - qa-auto-07-21-2026-integration-check
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "QA auto integration check OK - 07-21-2026"
